# - name: ilovenano
#   hosts: linux
#   tasks:
#     - name: install dependancies
#       apt:
#        name: 
#        - openjdk-8-jdk
#        - curl
#        - python3.8
#        state: latest


- name: install and set cassandra
  hosts: linux
  tasks:
    # - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - name: install dependancies
      yum:
       name:
      #  - java-1.8.0-openjdk
      #  - curl
      #  - initscripts
      #  - epel-release
      #  - firewalld
       - cassandra
       state: latest

    - name: install cassandra and fix systemctl
      shell: |
          sed -i -e 's/\r$//' /bin/systemctl
          systemctl stop cassandra
          rm -rf /var/lib/cassandra/data/system/*
      args:
        executable: /bin/bash

    - name: change cassandra config
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
      - {src: cassandra.yaml, dest: /etc/cassandra/conf/cassandra.yaml}
      - {src: cassandra.yaml, dest: /etc/cassandra/default.conf/cassandra.yaml}

    - name: change config_file
      replace:
        path: /etc/cassandra/conf/cassandra.yaml
        regexp: 'aremote-host-one'
        replace: "{{ ansible_default_ipv4.address }}"

    - name: change config_file_2
      replace:
        path: /etc/cassandra/default.conf/cassandra.yaml
        regexp: 'aremote-host-one'
        replace: "{{ ansible_default_ipv4.address }}"

    - name: start ufw
      ufw:
         state: enabled
         policy: allow
    
    - name: allow ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
      - 9142
        
    # - name: fix firewall setting
      # firewalld: 
      #     port: "{{item}}"
      #     state: enabled
      #     permanent: true
      #     immediate: true
      # with_items:
      # - 7000
      # - 7001
      # - 7199
      # - 9042
      # - 9160
      # - 9142
    
    - name: start cassandra
      service:
         name: cassandra
         state: started
